<?php

/**
 * PhaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phase');
    }
}