<?php

/**
 * TaskDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskDepartment');
    }
}