# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

updateProjectTask:
  url: /updateProjectTask
  param: { module: board, action: updateProjectTask }

# default rules
homepage:
  url:   /
  param: { module: board, action: index }