<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/11/20 22:38:33
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basedepartmentformfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/base/BaseDepartmentFormFilter.class.php',
  'basephaseformfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/base/BasePhaseFormFilter.class.php',
  'basetaskformfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/base/BaseTaskFormFilter.class.php',
  'baseformfilterdoctrine' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'departmentformfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/DepartmentFormFilter.class.php',
  'phaseformfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/PhaseFormFilter.class.php',
  'taskformfilter' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/filter/doctrine/TaskFormFilter.class.php',
  'baseform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/BaseForm.class.php',
  'basedepartmentform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/base/BaseDepartmentForm.class.php',
  'basephaseform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/base/BasePhaseForm.class.php',
  'basetaskform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/base/BaseTaskForm.class.php',
  'baseformdoctrine' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/BaseFormDoctrine.class.php',
  'departmentform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/DepartmentForm.class.php',
  'phaseform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/PhaseForm.class.php',
  'taskform' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/form/doctrine/TaskForm.class.php',

  // project_model
  'basedepartment' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/base/BaseDepartment.class.php',
  'basephase' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/base/BasePhase.class.php',
  'basetask' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/base/BaseTask.class.php',
  'department' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/Department.class.php',
  'departmenttable' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/DepartmentTable.class.php',
  'phase' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/Phase.class.php',
  'phasetable' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/PhaseTable.class.php',
  'task' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/Task.class.php',
  'tasktable' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/lib/model/doctrine/TaskTable.class.php',

  // application
  'myuser' => '/Applications/MAMP/htdocs/kanban/sf_sandbox/apps/frontend/lib/myUser.class.php',

  // modules
);
