# each task is broken down into phases 
Phase:
  actAs:
    Timestampable:
    Sluggable:
      fields: [slug]
  connection: doctrine
  tableName: phase
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(100)
    description:
      type: text
    slug:
      type: string(100)

# the smallest unit of work
Task:
  actAs:
    Timestampable:
    Sluggable:
      fields: [slug]
  connection: doctrine
  tableName: task
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(100)
    description:
      type: text
    slug:
      type: string(100)
    task_color:
      type: string(100)
    estimated_mins_to_complete:
      type: integer(8)
    actual_mins_to_complete:
      type: timestamp
    phase_id:
      type: integer(4)
    department_id:
      type: integer(4)
  relations:
    Phase:
      foreignAlias: Tasks
    Department:
      foreignAlias: Departments
  attributes:
    export: all
    validate: true
  
# who is responsible for the task
Department:
  actAs: [Timestampable]
  connection: doctrine
  tableName: department
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
     type: string(100)
    description:
      type: text
    short_name:
     type: string(100)
    task_color:
     type: string(100)
  relations:
    Tasks:
      foreignAlias: Departments
      class: Task
      refClass: TaskDepartment

TaskDepartment:
  actAs:
    Timestampable:
  connection: doctrine
  tableName: task_department
  columns:
    task_id:
      type: integer(4)
      primary: true    
    department_id:
      type: integer(4)
      primary: true    
  relations:
    Task:
      foreignAlias: TaskDepartments
    Department:
      foreignAlias: TaskDepartments